INPUT:
  DATA_ROOT: '/home/ly/data/datasets/human_parsing/CIHP/CIHP/instance-level_human_parsing'
  DATASET_NAME: 'CIHP'
  # INPUT_SIZE: [390,390]
  # INPUT_SIZE: [400,400]
  INPUT_SIZE: [448, 448]
  INPUT_MEAN: [0.485, 0.456, 0.406]
  INPUT_STD: [0.229, 0.224, 0.225]

TRAIN:
  GPU_IDS: [0,]
  BATCH_SIZE: 2
  EPOCHES: 200
  START_EPOCH: 0
  SNAPSHOT_DIR: './snapshots/cihp_shared/'
  # RESTORE_FROM: './snapshots/shared_test/test01_CIHP/CIHP_epoch_84.pth'
  RESTORE_FROM: './dataset/resnet101-imagenet.pth'
  NUM_CLASSES: 20

SOLVER:
  LEARNING_RATE: 1e-3
  WEIGHT_DECAY: 5e-4

MODEL:
  RES_TYPE: '101'
  WITH_DCN: [1, 1, 1]
  RESCORE_K: 31
  WITH_EDGE: True
  BUILD_MODEL: 'build_shared_patch_model'

TEST:
  SPLIT: 'val'
  BATCH_SIZE: 1
  GPU: [0,]
  INPUT_SIZE: [448, 448]
  RESTORE_FROM: '/home/ly/workspace/git/segmentation/human_parsing/TextureShapeParsing_CIHP/snapshots/shared_test/test01_CIHP_grids_448/patch2_2/CIHP_epoch_89.pth'
  #PRED_SAVE_DIR: './results/CIHP/mgdan'
  BUILD_MODEL: 'build_shared_patch_model'
  AUG_MIRROR: False
