INPUT:
  DATA_ROOT: '/home/ly/data/datasets/human_parsing/Pascal-Person-Part'
  DATASET_NAME: 'PASCAL_PERSON'
  INPUT_SIZE: [448, 448]
  INPUT_MEAN: [0.485, 0.456, 0.406]
  INPUT_STD: [0.229, 0.224, 0.225]
  NUM_CLASSES: 7

TRAIN:
  GPU_IDS: [0,1,2,3]
  BATCH_SIZE: 6
  EPOCHES: 200
  START_EPOCH: 0
  SNAPSHOT_DIR: './snapshots/pascal_shared/'
  RESTORE_FROM: './dataset/resnet101-imagenet.pth'
  NUM_CLASSES: 7

SOLVER:
  LEARNING_RATE: 1e-3
  WEIGHT_DECAY: 5e-4

MODEL:
  RES_TYPE: '101'
  WITH_DCN: [1, 1, 1]
  RESCORE_K: 31
  WITH_EDGE: True
  BUILD_MODEL: 'build_shared_edgeGrids_model'

TEST:
  SPLIT: 'val'
  BATCH_SIZE: 1
  GPU: [0,]
  INPUT_SIZE: [448, 448]
  AUG_MIRROR: True
  RESTORE_FROM: './trained_models/bestiou73.4665_PASCAL_PERSON_epoch_162.pth'
  #PRED_SAVE_DIR: './results/CIHP/mgdan'
  BUILD_MODEL: 'build_shared_edgeGrids_model'

