INPUT:
  # DATA_ROOT: '/home/ly/data/datasets/segmentation/pascal-parts/person_part/'
  DATA_ROOT: '/home/ly/data/datasets/human_parsing/Pascal-Person-Part'
  DATASET_NAME: 'PASCAL_PERSON'
  # INPUT_SIZE: [390,390]
  # INPUT_SIZE: [400,400]
  INPUT_SIZE: [448, 448]
  #INPUT_MEAN: [0.485, 0.456, 0.406]
  #INPUT_STD: [0.229, 0.224, 0.225]
  #PASCAL
  INPUT_MEAN: [0.446, 0.417, 0.387]
  INPUT_STD: [0.250, 0.242, 0.245]

TRAIN:
  GPU_IDS: [0,]
  BATCH_SIZE: 2
  EPOCHES: 200
  START_EPOCH: 0
  SNAPSHOT_DIR: './snapshots/pascal_shared/'
  # RESTORE_FROM: '/home/ly/workspace/git/segmentation/human_parsing/TextureShapeParsing_LIP/snapshots/shared_test/test01_startup/LIP_epoch_199.pth'
  RESTORE_FROM: './dataset/resnet101-imagenet.pth'
  NUM_CLASSES: 7

SOLVER:
  LEARNING_RATE: 1e-3
  WEIGHT_DECAY: 5e-4

MODEL:
  RES_TYPE: '101'
  WITH_DCN: [1, 1, 1]
  RESCORE_K: 31
  WITH_EDGE: True
  BUILD_MODEL: 'build_multiTask_model'

TEST:
  SPLIT: 'val'
  BATCH_SIZE: 1
  GPU: [0,]
  INPUT_SIZE: [448, 448]
  AUG_MIRROR: True
  RESTORE_FROM: '/home/ly/workspace/git/segmentation/human_parsing/MDCE_Pascal/snapshots/snapshots_pascal/indp_grids/edgeGrids22_448/bestiou_PASCAL_PERSON_epoch_174.pth'
  #PRED_SAVE_DIR: './results/CIHP/mgdan'
  BUILD_MODEL: 'build_multiTask_model'

