import os

from yacs.config import CfgNode as CN
_C = CN()

_C.MODEL = CN()
_C.TRAIN = CN()
_C.TEST = CN()
_C.INPUT = CN()
_C.SOLVER = CN()
_C.LABEL = CN()
_C.TPS = CN()
_C.VISUALIZE = CN()


_C.INPUT.DATA_ROOT = 'cityscapes'
_C.INPUT.DATASET_NAME = 'LIP'
_C.INPUT.DATA_LIST_PATH = './dataset/list/cityscapes/train.lst'
_C.INPUT.INPUT_SIZE = [512, 512]
_C.INPUT.DATA_PATH_LOG = ['train', 'val']
_C.INPUT.INPUT_MEAN = [0.446, 0.417, 0.387]
_C.INPUT.INPUT_STD = [0.250, 0.242, 0.245]

_C.INPUT.SCALE_MIN = 0.5
_C.INPUT.SCALE_MAX = 2
_C.INPUT.COLOR_AUG = 0.25
_C.INPUT.BBLUR = False
_C.INPUT.GBLUR = True
_C.INPUT.ROTATION_FACTOR = 30
_C.INPUT.NUM_CLASSES = 20

_C.TRAIN.BATCH_SIZE = 8
_C.TRAIN.START_EPOCH = 0
_C.TRAIN.EPOCHES = 200
_C.TRAIN.GPU_IDS = [0,]
_C.TRAIN.NUM_CLASSES = 20
_C.TRAIN.IGNORE_LABEL = 255
_C.TRAIN.RANDOM_MIRROR = True
_C.TRAIN.RANDOM_SCALE = True
_C.TRAIN.RESTORE_FROM = ''
_C.TRAIN.SNAPSHOT_TENSORBOARD_SAVE_NUM_IMAGES = 2
_C.TRAIN.SNAPSHOT_DIR = './snapshots/'
_C.TRAIN.RESTORE_FROM = './dataset/MS_DeepLab_resnet_pretrained_init.pth'

_C.TEST.SPLIT= 'eval'
_C.TEST.BATCH_SIZE = 1
_C.TEST.GPU = [0,]
_C.TEST.INPUT_SIZE = [384,384]
_C.TEST.EVAL_CKPTS = []
_C.TEST.EVAL_CKPTS_RANGE = []
_C.TEST.CKPT_DIR = './snapshots/'
_C.TEST.PRED_SAVE_DIR = ''
_C.TEST.BUILD_MODEL = ''
_C.TEST.RESTORE_FROM = ''
_C.TEST.AUG_MIRROR = False

_C.SOLVER.LR_POWER = 0.9
_C.SOLVER.WEIGHT_DECAY = 5e-4
_C.SOLVER.LEARNING_RATE = 1e-3
_C.SOLVER.MOMENTUM = 0.9

_C.MODEL.WITH_FG = True
_C.MODEL.WITH_EDGE = True
#For pascal person,
# 0:background, 1:head, 2:torso, 3:lower arm, 4:upper arm, 5:lower leg, 6:upper leg
_C.MODEL.RES_TYPE = 101
_C.MODEL.WITH_DCN = [1, 1, 1]
_C.MODEL.WITH_EDGE = True
_C.MODEL.BACKBONE = 'resnet'
_C.MODEL.WITH_RESCORE = True
_C.MODEL.RESCORE_K = 1
_C.MODEL.WITH_MASK_ATTEN = True
_C.MODEL.WITH_MASK_EDGE = True
_C.MODEL.WITH_MASK_PARS = True
_C.MODEL.BUILD_MODEL = ''

_C.VISUALIZE.SAVE_IMAGES_NUM = 2